Working on travis logic

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -33,10 +33,9 @@ script:
   - doit small_data_setup --name $DIR
   - cd $DIR
   - if ! anaconda-project list-downloads | grep -q 'No downloads'; then
-      if [ -d data ]; then
-        echo 'FAIL needs data and no test data found'
-        exit 1
-      fi
+      if ! [ -d data ]; then
+        echo 'FAIL needs data and no test data found' && exit 1;
+      fi;
     fi
   - anaconda-project run lint
   - anaconda-project run test
