Fixing up doit and travis to only fail if data is needed and not present

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -32,7 +32,13 @@ before_install:
 script:
   - doit small_data_setup --name $DIR
   - cd $DIR
-  - anaconda-project list-downloads | grep 'No downloads' || echo 'FAIL needs data and no test data found' && exit 1
+  - anaconda-project list-downloads | grep 'No downloads' && exit 0 || echo 'FAIL needs data and no test data found' && exit 1
+  - if ! anaconda-project list-downloads | grep -q 'No downloads'; then
+      if [ -d data ]; then
+        echo 'FAIL needs data and no test data found'
+        exit 1
+      fi
+    fi
   - anaconda-project run lint
   - anaconda-project run test
   - cd ..
